/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package betess;

import java.text.DecimalFormat;
import java.util.*;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.table.DefaultTableModel;


public class AreaCliente extends javax.swing.JFrame {
    
    private BetESS betess;

    public void setBetess(BetESS betess) {
        this.betess = betess;
        this.setTitle("Área autenticada");
    }

    /**
     * Creates new form AreaCliente
     */
    public AreaCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcoes_aposta = new javax.swing.ButtonGroup();
        Welcome_label = new javax.swing.JLabel();
        buttons_panel = new javax.swing.JPanel();
        apostar_button = new javax.swing.JButton();
        ver_apostas_button = new javax.swing.JButton();
        creditos_button = new javax.swing.JButton();
        notificacoes_button = new javax.swing.JButton();
        editar_perfil_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        logout_button = new javax.swing.JButton();
        options_panel = new javax.swing.JPanel();
        apostar_elements = new javax.swing.JPanel();
        submit_aposta_button = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        quantia_field = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ganhos_field = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        events_list = new javax.swing.JTable();
        casa_button = new javax.swing.JRadioButton();
        empate_button = new javax.swing.JRadioButton();
        fora_button = new javax.swing.JRadioButton();
        apostas_elements = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        lista_apostas_pane = new javax.swing.JScrollPane();
        lista_apostas = new javax.swing.JTable();
        cashout_button = new javax.swing.JButton();
        creditos_elements = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        saldo_field = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        creditos_field = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        creditar_button = new javax.swing.JButton();
        notificacoes_elements = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        notificacoes_list = new javax.swing.JTable();
        descartar_button = new javax.swing.JButton();
        edit_perfil_elements = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nome_field = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        email_field = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        palavra_passe_field = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        contacto_field = new javax.swing.JTextField();
        edit_dados_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Welcome_label.setText("Bem-vindo à BetESS");

        apostar_button.setText("Apostar");
        apostar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apostar_buttonActionPerformed(evt);
            }
        });

        ver_apostas_button.setText("Minhas apostas");
        ver_apostas_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_apostas_buttonActionPerformed(evt);
            }
        });

        creditos_button.setText("Créditos");
        creditos_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditos_buttonActionPerformed(evt);
            }
        });

        notificacoes_button.setText("Notificações");
        notificacoes_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificacoes_buttonActionPerformed(evt);
            }
        });

        editar_perfil_button.setText("Editar Perfil");
        editar_perfil_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editar_perfil_buttonActionPerformed(evt);
            }
        });

        jLabel1.setText("Menu:");

        logout_button.setText("Terminar sessão");
        logout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttons_panelLayout = new javax.swing.GroupLayout(buttons_panel);
        buttons_panel.setLayout(buttons_panelLayout);
        buttons_panelLayout.setHorizontalGroup(
            buttons_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttons_panelLayout.createSequentialGroup()
                .addGroup(buttons_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buttons_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(buttons_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editar_perfil_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(apostar_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(creditos_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(notificacoes_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ver_apostas_button, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)))
                    .addGroup(buttons_panelLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(buttons_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logout_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        buttons_panelLayout.setVerticalGroup(
            buttons_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttons_panelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(apostar_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ver_apostas_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(creditos_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notificacoes_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editar_perfil_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout_button)
                .addContainerGap())
        );

        options_panel.setLayout(new java.awt.CardLayout());

        submit_aposta_button.setText("Apostar");
        submit_aposta_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_aposta_buttonActionPerformed(evt);
            }
        });

        jLabel6.setText("Quantia:");

        quantia_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantia_fieldActionPerformed(evt);
            }
        });

        jLabel7.setText("€ (euros)");

        jLabel8.setText("Ganhos possíveis:");

        ganhos_field.setEditable(false);
        ganhos_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ganhos_fieldActionPerformed(evt);
            }
        });

        events_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Evento número", "Casa", "Fora", "Odd Casa", "Odd Fora", "Odd Empate"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(events_list);
        if (events_list.getColumnModel().getColumnCount() > 0) {
            events_list.getColumnModel().getColumn(0).setResizable(false);
            events_list.getColumnModel().getColumn(1).setResizable(false);
            events_list.getColumnModel().getColumn(2).setResizable(false);
            events_list.getColumnModel().getColumn(3).setResizable(false);
            events_list.getColumnModel().getColumn(4).setResizable(false);
            events_list.getColumnModel().getColumn(5).setResizable(false);
        }

        jScrollPane1.setViewportView(jScrollPane2);

        opcoes_aposta.add(casa_button);
        casa_button.setText("Casa");
        casa_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casa_buttonActionPerformed(evt);
            }
        });

        opcoes_aposta.add(empate_button);
        empate_button.setText("Empate");
        empate_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empate_buttonActionPerformed(evt);
            }
        });

        opcoes_aposta.add(fora_button);
        fora_button.setText("Fora");
        fora_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fora_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout apostar_elementsLayout = new javax.swing.GroupLayout(apostar_elements);
        apostar_elements.setLayout(apostar_elementsLayout);
        apostar_elementsLayout.setHorizontalGroup(
            apostar_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(apostar_elementsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(apostar_elementsLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(apostar_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(apostar_elementsLayout.createSequentialGroup()
                        .addComponent(casa_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fora_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(empate_button)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(apostar_elementsLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quantia_field, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ganhos_field, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                        .addComponent(submit_aposta_button)
                        .addGap(36, 36, 36))))
        );
        apostar_elementsLayout.setVerticalGroup(
            apostar_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(apostar_elementsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(apostar_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(quantia_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(submit_aposta_button)
                    .addComponent(jLabel8)
                    .addComponent(ganhos_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(apostar_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(casa_button)
                    .addComponent(fora_button)
                    .addComponent(empate_button))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        options_panel.add(apostar_elements, "card2");

        jLabel13.setText("Minhas apostas");

        lista_apostas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificador", "Equipa Casa", "Equipa Fora", "Vitória Casa", "Vitória Fora", "Empate", "Quantia", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        lista_apostas_pane.setViewportView(lista_apostas);
        if (lista_apostas.getColumnModel().getColumnCount() > 0) {
            lista_apostas.getColumnModel().getColumn(0).setResizable(false);
            lista_apostas.getColumnModel().getColumn(1).setResizable(false);
            lista_apostas.getColumnModel().getColumn(2).setResizable(false);
            lista_apostas.getColumnModel().getColumn(3).setResizable(false);
            lista_apostas.getColumnModel().getColumn(4).setResizable(false);
            lista_apostas.getColumnModel().getColumn(5).setResizable(false);
            lista_apostas.getColumnModel().getColumn(6).setResizable(false);
            lista_apostas.getColumnModel().getColumn(7).setResizable(false);
        }

        cashout_button.setText("Cashout");
        cashout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashout_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout apostas_elementsLayout = new javax.swing.GroupLayout(apostas_elements);
        apostas_elements.setLayout(apostas_elementsLayout);
        apostas_elementsLayout.setHorizontalGroup(
            apostas_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(apostas_elementsLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(apostas_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cashout_button)
                    .addGroup(apostas_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lista_apostas_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        apostas_elementsLayout.setVerticalGroup(
            apostas_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(apostas_elementsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(lista_apostas_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cashout_button)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        options_panel.add(apostas_elements, "card2");

        jLabel9.setText("Saldo Atual:");

        saldo_field.setEditable(false);
        saldo_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldo_fieldActionPerformed(evt);
            }
        });

        jLabel10.setText("€ (euros)");

        jLabel11.setText("Creditar");

        jLabel12.setText("€ (euros)");

        creditar_button.setText("Creditar");
        creditar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditar_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout creditos_elementsLayout = new javax.swing.GroupLayout(creditos_elements);
        creditos_elements.setLayout(creditos_elementsLayout);
        creditos_elementsLayout.setHorizontalGroup(
            creditos_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creditos_elementsLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(creditos_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(creditos_elementsLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(creditos_field, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12))
                    .addGroup(creditos_elementsLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saldo_field, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, creditos_elementsLayout.createSequentialGroup()
                .addContainerGap(342, Short.MAX_VALUE)
                .addComponent(creditar_button)
                .addGap(275, 275, 275))
        );
        creditos_elementsLayout.setVerticalGroup(
            creditos_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creditos_elementsLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(creditos_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(saldo_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(57, 57, 57)
                .addGroup(creditos_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(creditos_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addComponent(creditar_button)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        options_panel.add(creditos_elements, "card2");

        jLabel14.setText("Notificações:");

        notificacoes_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificador Evento", "Identificador Aposta", "Equipa Casa", "Equipa Fora", "Quantia aposta", "Balanço", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(notificacoes_list);
        if (notificacoes_list.getColumnModel().getColumnCount() > 0) {
            notificacoes_list.getColumnModel().getColumn(0).setResizable(false);
            notificacoes_list.getColumnModel().getColumn(1).setResizable(false);
            notificacoes_list.getColumnModel().getColumn(2).setResizable(false);
            notificacoes_list.getColumnModel().getColumn(3).setResizable(false);
            notificacoes_list.getColumnModel().getColumn(4).setResizable(false);
            notificacoes_list.getColumnModel().getColumn(5).setResizable(false);
            notificacoes_list.getColumnModel().getColumn(6).setResizable(false);
        }

        descartar_button.setText("Descartar");
        descartar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descartar_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout notificacoes_elementsLayout = new javax.swing.GroupLayout(notificacoes_elements);
        notificacoes_elements.setLayout(notificacoes_elementsLayout);
        notificacoes_elementsLayout.setHorizontalGroup(
            notificacoes_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notificacoes_elementsLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(notificacoes_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(descartar_button)
                    .addGroup(notificacoes_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel14)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        notificacoes_elementsLayout.setVerticalGroup(
            notificacoes_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notificacoes_elementsLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel14)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(descartar_button)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        options_panel.add(notificacoes_elements, "card2");

        jLabel2.setText("Nome:");

        nome_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_fieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Email:");

        email_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_fieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Palavra-Passe:");

        palavra_passe_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                palavra_passe_fieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Contacto:");

        contacto_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contacto_fieldActionPerformed(evt);
            }
        });

        edit_dados_button.setText("Editar Dados");
        edit_dados_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_dados_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout edit_perfil_elementsLayout = new javax.swing.GroupLayout(edit_perfil_elements);
        edit_perfil_elements.setLayout(edit_perfil_elementsLayout);
        edit_perfil_elementsLayout.setHorizontalGroup(
            edit_perfil_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edit_perfil_elementsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(edit_perfil_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(edit_perfil_elementsLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contacto_field, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(edit_perfil_elementsLayout.createSequentialGroup()
                        .addGroup(edit_perfil_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(edit_perfil_elementsLayout.createSequentialGroup()
                                .addGroup(edit_perfil_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(28, 28, 28)
                                .addGroup(edit_perfil_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(email_field)
                                    .addComponent(nome_field)))
                            .addGroup(edit_perfil_elementsLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(palavra_passe_field)))
                        .addGap(6, 6, 6))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, edit_perfil_elementsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(edit_dados_button)
                .addContainerGap())
        );
        edit_perfil_elementsLayout.setVerticalGroup(
            edit_perfil_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edit_perfil_elementsLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(edit_perfil_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nome_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(edit_perfil_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(email_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(edit_perfil_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(palavra_passe_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(edit_perfil_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(contacto_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(edit_dados_button)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        options_panel.add(edit_perfil_elements, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttons_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(options_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(Welcome_label)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 15, Short.MAX_VALUE)
                        .addComponent(Welcome_label)
                        .addGap(18, 18, 18)
                        .addComponent(options_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttons_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editar_perfil_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editar_perfil_buttonActionPerformed
        Jogador autenticado = this.betess.checkUser(this.betess.getId_utilizador_aut());
        
        nome_field.setText(autenticado.getNome());
        email_field.setText(autenticado.getEmail());
        contacto_field.setText(autenticado.getContacto());
        
        /* remoção de paineis anteriores */
        options_panel.removeAll();
        options_panel.repaint();
        options_panel.revalidate();
        
        /* alocação do respetivo painel de opções */
        options_panel.add(edit_perfil_elements);
        options_panel.repaint();
        options_panel.revalidate();
        
        
    }//GEN-LAST:event_editar_perfil_buttonActionPerformed

    private void ver_apostas_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_apostas_buttonActionPerformed
        /* remoção de paineis anteriores */
        options_panel.removeAll();
        options_panel.repaint();
        options_panel.revalidate();
        
        /* alocação do respetivo painel de opções */
        options_panel.add(apostas_elements);
        options_panel.repaint();
        options_panel.revalidate();
        
        List<Aposta> apostas = this.betess.getApostasJogador(this.betess.getId_utilizador_aut());
        
        DefaultTableModel model = (DefaultTableModel) lista_apostas.getModel();
        
        model.setRowCount(0);
        
        DecimalFormat dc = new DecimalFormat("0.00");
        
        for (Aposta a : apostas){
            EventoDesportivo e = this.betess.getEventoDesportivo(a.getId_evento());;
            model.addRow(new Object[]{a.getId_evento(), e.getequipa_casa(), e.getequipa_fora(), a.getGanha_casa(), a.getGanha_fora(), a.getEmpate(), Double.parseDouble(dc.format(a.getQuantia())), a.getEstado()});
        }
        
        
    }//GEN-LAST:event_ver_apostas_buttonActionPerformed

    private void apostar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apostar_buttonActionPerformed
        /* remoção de paineis anteriores */
        options_panel.removeAll();
        options_panel.repaint();
        options_panel.revalidate();
        
        /* alocação do respetivo painel de opções */
        options_panel.add(apostar_elements);
        options_panel.repaint();
        options_panel.revalidate();
        
        Map<Integer, EventoDesportivo> eventos = this.betess.getEventosDesportivos();
        
        DefaultTableModel model = (DefaultTableModel) events_list.getModel();
        
        model.setRowCount(0);
        
        for (EventoDesportivo e : eventos.values()){
            String equipa_casa = this.betess.getEquipa(e.getequipa_casa()).getDesignacao();
            String equipa_fora = this.betess.getEquipa(e.getequipa_fora()).getDesignacao();
            model.addRow(new Object[]{e.getId_evento(), equipa_casa, equipa_fora, e.getOdd_casa(), e.getOdd_fora(), e.getOdd_empate()});
        }
    }//GEN-LAST:event_apostar_buttonActionPerformed

    private void nome_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_fieldActionPerformed
        
    }//GEN-LAST:event_nome_fieldActionPerformed

    private void email_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_fieldActionPerformed

    private void palavra_passe_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_palavra_passe_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_palavra_passe_fieldActionPerformed

    private void contacto_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contacto_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contacto_fieldActionPerformed

    private void edit_dados_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_dados_buttonActionPerformed
        
        if (!nome_field.getText().isEmpty() &&
            !email_field.getText().isEmpty() &&
            !palavra_passe_field.getText().isEmpty() &&
            contacto_field.getText().isEmpty()){

            Jogador autenticado = this.betess.checkUser(this.betess.getId_utilizador_aut());

            autenticado.setNome(nome_field.getText());
            autenticado.setEmail(email_field.getText());
            autenticado.setPassword(palavra_passe_field.getText());
            autenticado.setContacto(contacto_field.getText());
        }
        else {
            JOptionPane.showMessageDialog(null, "Existem campos do formulário não preenchidos.", "Erro!", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_edit_dados_buttonActionPerformed

    private void submit_aposta_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_aposta_buttonActionPerformed
        
        if (!quantia_field.getText().isEmpty() && (opcoes_aposta.getSelection() != null)){

            String user = this.betess.getId_utilizador_aut();
            Jogador j = this.betess.checkUser(user);

            if (j.getSaldo() >= Double.parseDouble(quantia_field.getText())){

                DefaultTableModel model = (DefaultTableModel) events_list.getModel();

                int row = events_list.getSelectedRow();

                int id_evento = (int)model.getValueAt(row, 0);

                boolean casa_selected = casa_button.isSelected();
                boolean fora_selected = fora_button.isSelected();
                boolean empate_selected = empate_button.isSelected();

                boolean aposta_permitida = true;
                for (Aposta a : this.betess.getApostasJogador(user)){
                    if (a.getId_evento() == id_evento){
                        aposta_permitida = false;
                        break;
                    }
                }

                if (aposta_permitida){
                    this.betess.registaAposta(Double.parseDouble(quantia_field.getText()), id_evento, user, casa_selected, fora_selected, empate_selected);

                    JOptionPane.showMessageDialog(null, "Aposta registada com sucesso.", "BetESS", JOptionPane.PLAIN_MESSAGE);
                }
                else {
                    JOptionPane.showMessageDialog(null, "Já tem uma aposta registada para o evento selecionado.", "Falha no registo da aposta", JOptionPane.ERROR_MESSAGE);
                }
            }
            else {
                JOptionPane.showMessageDialog(null, "Créditos insuficientes.", "Falha no registo da aposta", JOptionPane.ERROR_MESSAGE);
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Existem campos do formulário não preenchidos.", "Erro!", ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_submit_aposta_buttonActionPerformed

    private void quantia_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantia_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantia_fieldActionPerformed

    private void casa_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casa_buttonActionPerformed
        DefaultTableModel model = (DefaultTableModel) events_list.getModel(); 
        int row = events_list.getSelectedRow();
        
        double odd_casa = (double)model.getValueAt(row, 3);
        
        DecimalFormat dc = new DecimalFormat("0.00");
        
        ganhos_field.setText(dc.format(odd_casa * Double.parseDouble(quantia_field.getText())));
    }//GEN-LAST:event_casa_buttonActionPerformed

    private void fora_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fora_buttonActionPerformed
        DefaultTableModel model = (DefaultTableModel) events_list.getModel(); 
        int row = events_list.getSelectedRow();
        
        double odd_fora = (double)model.getValueAt(row, 4);
        
        DecimalFormat dc = new DecimalFormat("0.00");
        
        ganhos_field.setText(dc.format(Double.toString(odd_fora * Double.parseDouble(quantia_field.getText()))));
    }//GEN-LAST:event_fora_buttonActionPerformed

    private void empate_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empate_buttonActionPerformed
        DefaultTableModel model = (DefaultTableModel) events_list.getModel(); 
        int row = events_list.getSelectedRow();
        
        double odd_empate = (double)model.getValueAt(row, 5);
        
        DecimalFormat dc = new DecimalFormat("0.00");
        
        ganhos_field.setText(dc.format(Double.toString(odd_empate * Double.parseDouble(quantia_field.getText()))));
    }//GEN-LAST:event_empate_buttonActionPerformed

    private void saldo_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldo_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saldo_fieldActionPerformed

    private void creditar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditar_buttonActionPerformed
        
        if (!creditos_field.getText().isEmpty()){

            double creditos = Double.parseDouble(creditos_field.getText());

            this.betess.atualizaSaldo(creditos, this.betess.getId_utilizador_aut());
        }
        else {
            JOptionPane.showMessageDialog(null, "Existem campos do formulário não preenchidos.", "Erro!", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_creditar_buttonActionPerformed

    private void descartar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descartar_buttonActionPerformed
        
        if (notificacoes_list.getSelectedRow() != -1){

            DefaultTableModel model = (DefaultTableModel) notificacoes_list.getModel(); 
            int row = notificacoes_list.getSelectedRow();

            model.removeRow(row);
            /* falta descartar a notificação no objeto jogador */
            this.betess.removeNotificacao(this.betess.getId_utilizador_aut(), (int) model.getValueAt(row, 1));
        }
        else {
            JOptionPane.showMessageDialog(null, "Selecione uma das notificações.", "Erro!", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_descartar_buttonActionPerformed

    private void notificacoes_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificacoes_buttonActionPerformed
        /* remoção de paineis anteriores */
        options_panel.removeAll();
        options_panel.repaint();
        options_panel.revalidate();
        
        /* alocação do respetivo painel de opções */
        options_panel.add(notificacoes_elements);
        options_panel.repaint();
        options_panel.revalidate();
        
        Jogador j = this.betess.checkUser(this.betess.getId_utilizador_aut());
        
        List<Notificacao> notificacoes = j.getNotificacoes();
        
        DefaultTableModel model = (DefaultTableModel) notificacoes_list.getModel();
        
        model.setRowCount(0);
        
        DecimalFormat dc = new DecimalFormat("0.00");
        
        for (Notificacao n : notificacoes){
            Aposta a = this.betess.getAposta(n.getId_aposta());
            EventoDesportivo e = this.betess.getEventoDesportivo(a.getId_evento());
            String equipa_casa = e.getequipa_casa();
            String equipa_fora = e.getequipa_fora();
            
            model.addRow(new Object[]{a.getId_evento(), a.getId_aposta(), equipa_casa, equipa_fora, Double.parseDouble(dc.format(a.getQuantia())), n.getBalanco(), n.getStatus()});
        }
    }//GEN-LAST:event_notificacoes_buttonActionPerformed

    private void logout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_buttonActionPerformed
        this.betess.setId_utilizador_aut("None");
        this.setVisible(false);
        
        /* local onde o estado da aplicação é guardado */
        this.betess.save();
    }//GEN-LAST:event_logout_buttonActionPerformed

    private void creditos_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditos_buttonActionPerformed
        /* remoção de paineis anteriores */
        options_panel.removeAll();
        options_panel.repaint();
        options_panel.revalidate();
        
        /* alocação do respetivo painel de opções */
        options_panel.add(creditos_elements);
        options_panel.repaint();
        options_panel.revalidate();
        
        DecimalFormat dc = new DecimalFormat("0.00");
        
        saldo_field.setText(dc.format(this.betess.checkUser(this.betess.getId_utilizador_aut()).getSaldo()));
    }//GEN-LAST:event_creditos_buttonActionPerformed

    private void ganhos_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ganhos_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ganhos_fieldActionPerformed

    private void cashout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashout_buttonActionPerformed
        
        if (lista_apostas.getSelectedRow() != -1){

            int row = lista_apostas.getSelectedRow();

            DefaultTableModel model = (DefaultTableModel) lista_apostas.getModel();
            
            String estado = (String) model.getValueAt(row, 7);
            
            if (estado.equals("Não paga")){

                this.betess.removeAposta((int) model.getValueAt(row, 0));

                Double saldo = this.betess.checkUser(this.betess.getId_utilizador_aut()).getSaldo();
                Double valor_aposta = (double) model.getValueAt(row, 6);
                Double novo_saldo = saldo - (0.8 * valor_aposta);

                saldo -= novo_saldo;
                this.betess.atualizaSaldo(saldo, this.betess.getId_utilizador_aut());

                model.removeRow(row);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Selecione uma aposta!", "Erro!", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cashout_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AreaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AreaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AreaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AreaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AreaCliente main = new AreaCliente();
                main.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Welcome_label;
    private javax.swing.JButton apostar_button;
    private javax.swing.JPanel apostar_elements;
    private javax.swing.JPanel apostas_elements;
    private javax.swing.JPanel buttons_panel;
    private javax.swing.JRadioButton casa_button;
    private javax.swing.JButton cashout_button;
    private javax.swing.JTextField contacto_field;
    private javax.swing.JButton creditar_button;
    private javax.swing.JButton creditos_button;
    private javax.swing.JPanel creditos_elements;
    private javax.swing.JTextField creditos_field;
    private javax.swing.JButton descartar_button;
    private javax.swing.JButton edit_dados_button;
    private javax.swing.JPanel edit_perfil_elements;
    private javax.swing.JButton editar_perfil_button;
    private javax.swing.JTextField email_field;
    private javax.swing.JRadioButton empate_button;
    private javax.swing.JTable events_list;
    private javax.swing.JRadioButton fora_button;
    private javax.swing.JTextField ganhos_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable lista_apostas;
    private javax.swing.JScrollPane lista_apostas_pane;
    private javax.swing.JButton logout_button;
    private javax.swing.JTextField nome_field;
    private javax.swing.JButton notificacoes_button;
    private javax.swing.JPanel notificacoes_elements;
    private javax.swing.JTable notificacoes_list;
    private javax.swing.ButtonGroup opcoes_aposta;
    private javax.swing.JPanel options_panel;
    private javax.swing.JTextField palavra_passe_field;
    private javax.swing.JTextField quantia_field;
    private javax.swing.JTextField saldo_field;
    private javax.swing.JButton submit_aposta_button;
    private javax.swing.JButton ver_apostas_button;
    // End of variables declaration//GEN-END:variables
}
