/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package betess;

import java.util.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MarcoSilva
 */
public class AreaAdministrador extends javax.swing.JFrame {
    
    private BetESS betess;

    public void setBetess(BetESS betess) {
        this.betess = betess;
        Welcome_label.setText("Bem vindo " + this.betess.checkUser(this.betess.getId_utilizador_aut()).getNome());

    }

    /**
     * Creates new form AreaCliente
     */
    public AreaAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcoes_aposta = new javax.swing.ButtonGroup();
        Welcome_label = new javax.swing.JLabel();
        buttons_panel = new javax.swing.JPanel();
        ver_jogadores_button = new javax.swing.JButton();
        eventos_desportivos_button = new javax.swing.JButton();
        jogadores_bloq_button = new javax.swing.JButton();
        apostas_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        options_panel = new javax.swing.JPanel();
        ver_jogadores_elements = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jogadores_list = new javax.swing.JTable();
        remover_jogador_button = new javax.swing.JButton();
        bloquear_jogador_button = new javax.swing.JButton();
        eventos_desportivos_elements = new javax.swing.JPanel();
        jogadores_bloqueados_elements = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        desbloquear_jogador_button = new javax.swing.JButton();
        apostas_elements = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lista_apostas = new javax.swing.JTable();
        elimina_aposta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Welcome_label.setText("Administração do Sistema");

        ver_jogadores_button.setText("Ver Jogadores");
        ver_jogadores_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_jogadores_buttonActionPerformed(evt);
            }
        });

        eventos_desportivos_button.setText("Eventos Desportivos");
        eventos_desportivos_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventos_desportivos_buttonActionPerformed(evt);
            }
        });

        jogadores_bloq_button.setText("Jogadores Bloqueados");

        apostas_button.setText("Apostas");
        apostas_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apostas_buttonActionPerformed(evt);
            }
        });

        jLabel1.setText("Menu:");

        javax.swing.GroupLayout buttons_panelLayout = new javax.swing.GroupLayout(buttons_panel);
        buttons_panel.setLayout(buttons_panelLayout);
        buttons_panelLayout.setHorizontalGroup(
            buttons_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttons_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttons_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ver_jogadores_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jogadores_bloq_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(apostas_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eventos_desportivos_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttons_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(69, 69, 69))
        );
        buttons_panelLayout.setVerticalGroup(
            buttons_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttons_panelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(ver_jogadores_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eventos_desportivos_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jogadores_bloq_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(apostas_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        options_panel.setLayout(new java.awt.CardLayout());

        jLabel2.setText("Lista de Jogadores registados no sistema");

        jogadores_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Email", "Nome", "Contacto", "Saldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jogadores_list);
        if (jogadores_list.getColumnModel().getColumnCount() > 0) {
            jogadores_list.getColumnModel().getColumn(0).setResizable(false);
            jogadores_list.getColumnModel().getColumn(1).setResizable(false);
            jogadores_list.getColumnModel().getColumn(2).setResizable(false);
            jogadores_list.getColumnModel().getColumn(3).setResizable(false);
        }

        remover_jogador_button.setText("Remover");
        remover_jogador_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remover_jogador_buttonActionPerformed(evt);
            }
        });

        bloquear_jogador_button.setText("Bloquear");
        bloquear_jogador_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloquear_jogador_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ver_jogadores_elementsLayout = new javax.swing.GroupLayout(ver_jogadores_elements);
        ver_jogadores_elements.setLayout(ver_jogadores_elementsLayout);
        ver_jogadores_elementsLayout.setHorizontalGroup(
            ver_jogadores_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ver_jogadores_elementsLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(ver_jogadores_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(ver_jogadores_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(ver_jogadores_elementsLayout.createSequentialGroup()
                            .addComponent(bloquear_jogador_button)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(remover_jogador_button))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        ver_jogadores_elementsLayout.setVerticalGroup(
            ver_jogadores_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ver_jogadores_elementsLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ver_jogadores_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(remover_jogador_button)
                    .addComponent(bloquear_jogador_button))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        options_panel.add(ver_jogadores_elements, "card2");

        javax.swing.GroupLayout eventos_desportivos_elementsLayout = new javax.swing.GroupLayout(eventos_desportivos_elements);
        eventos_desportivos_elements.setLayout(eventos_desportivos_elementsLayout);
        eventos_desportivos_elementsLayout.setHorizontalGroup(
            eventos_desportivos_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 697, Short.MAX_VALUE)
        );
        eventos_desportivos_elementsLayout.setVerticalGroup(
            eventos_desportivos_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );

        options_panel.add(eventos_desportivos_elements, "card2");

        jLabel3.setText("Jogadores Bloqueados na Plataforma");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Email", "Nome", "Contacto", "Saldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        desbloquear_jogador_button.setText("Desbloquear Jogador");
        desbloquear_jogador_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desbloquear_jogador_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jogadores_bloqueados_elementsLayout = new javax.swing.GroupLayout(jogadores_bloqueados_elements);
        jogadores_bloqueados_elements.setLayout(jogadores_bloqueados_elementsLayout);
        jogadores_bloqueados_elementsLayout.setHorizontalGroup(
            jogadores_bloqueados_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jogadores_bloqueados_elementsLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jogadores_bloqueados_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(desbloquear_jogador_button)
                    .addGroup(jogadores_bloqueados_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jogadores_bloqueados_elementsLayout.setVerticalGroup(
            jogadores_bloqueados_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jogadores_bloqueados_elementsLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(desbloquear_jogador_button)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        options_panel.add(jogadores_bloqueados_elements, "card2");

        jLabel4.setText("Apostas");

        lista_apostas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Identificador", "Identificador Evento", "Identificador Jogador", "Ganha Casa", "Ganha Fora", "Empate", "Quantia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(lista_apostas);

        elimina_aposta.setText("Eliminar");
        elimina_aposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elimina_apostaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout apostas_elementsLayout = new javax.swing.GroupLayout(apostas_elements);
        apostas_elements.setLayout(apostas_elementsLayout);
        apostas_elementsLayout.setHorizontalGroup(
            apostas_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(apostas_elementsLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(apostas_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(elimina_aposta)
                    .addGroup(apostas_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        apostas_elementsLayout.setVerticalGroup(
            apostas_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(apostas_elementsLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(elimina_aposta)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        options_panel.add(apostas_elements, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttons_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(Welcome_label)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(options_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Welcome_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(options_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttons_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eventos_desportivos_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventos_desportivos_buttonActionPerformed
        /* remoção de paineis anteriores */
        options_panel.removeAll();
        options_panel.repaint();
        options_panel.revalidate();
        
        /* alocação do respetivo painel de opções */
        options_panel.add(eventos_desportivos_elements);
        options_panel.repaint();
        options_panel.revalidate();
        
        
    }//GEN-LAST:event_eventos_desportivos_buttonActionPerformed

    private void ver_jogadores_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_jogadores_buttonActionPerformed
        /* remoção de paineis anteriores */
        options_panel.removeAll();
        options_panel.repaint();
        options_panel.revalidate();
        
        /* alocação do respetivo painel de opções */
        options_panel.add(ver_jogadores_elements);
        options_panel.repaint();
        options_panel.revalidate();
        
        HashMap<String, Jogador> jogadores = this.betess.getJogadores();
        
        DefaultTableModel model = (DefaultTableModel) jogadores_list.getModel();
        
        for (Jogador j : jogadores.values()){
            model.addRow(new Object[]{j.getEmail(), j.getNome(), j.getContacto(), j.getSaldo()});
        }
        
    }//GEN-LAST:event_ver_jogadores_buttonActionPerformed

    private void apostas_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apostas_buttonActionPerformed
        /* remoção de paineis anteriores */
        options_panel.removeAll();
        options_panel.repaint();
        options_panel.revalidate();
        
        /* alocação do respetivo painel de opções */
        options_panel.add(apostas_elements);
        options_panel.repaint();
        options_panel.revalidate();
        
        HashMap<Integer, Aposta> apostas = this.betess.getApostas();
        
        DefaultTableModel model = (DefaultTableModel) lista_apostas.getModel();
        
        for (Aposta a : apostas.values()){
            EventoDesportivo e = this.betess.getEventoDesportivo(a.getId_evento());
            /*String equipa_casa = this.betess.getEquipa(e.getId_equipa_casa()).getDesignacao();
            String equipa_fora = this.betess.getEquipa(e.getId_equipa_fora()).getDesignacao();*/
            model.addRow(new Object[]{a.getId_aposta(), a.getId_evento(), a.getId_jogador(), a.getGanha_casa(), a.getGanha_fora(), a.getEmpate(), a.getQuantia()});
        }
        
    }//GEN-LAST:event_apostas_buttonActionPerformed

    private void remover_jogador_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remover_jogador_buttonActionPerformed
        int row = jogadores_list.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jogadores_list.getModel();
        
        this.betess.eliminaJogador((String) jogadores_list.getValueAt(row, 0));
        model.removeRow(row);
    }//GEN-LAST:event_remover_jogador_buttonActionPerformed

    private void bloquear_jogador_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloquear_jogador_buttonActionPerformed
        int row = jogadores_list.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jogadores_list.getModel();
        
        this.betess.bloqueiaJogador((String) jogadores_list.getValueAt(row, 0));
        model.removeRow(row);
    }//GEN-LAST:event_bloquear_jogador_buttonActionPerformed

    private void desbloquear_jogador_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desbloquear_jogador_buttonActionPerformed
        int row = jogadores_list.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jogadores_list.getModel();
        
        this.betess.desbloqueiaJogador((String) jogadores_list.getValueAt(row, 0));
        model.removeRow(row);
    }//GEN-LAST:event_desbloquear_jogador_buttonActionPerformed

    private void elimina_apostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elimina_apostaActionPerformed
        int row = jogadores_list.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) lista_apostas.getModel();
        
        this.betess.removeAposta((int)lista_apostas.getValueAt(row, 0));
        model.removeRow(row);
    }//GEN-LAST:event_elimina_apostaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AreaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AreaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AreaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AreaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AreaAdministrador main = new AreaAdministrador();
                main.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Welcome_label;
    private javax.swing.JButton apostas_button;
    private javax.swing.JPanel apostas_elements;
    private javax.swing.JButton bloquear_jogador_button;
    private javax.swing.JPanel buttons_panel;
    private javax.swing.JButton desbloquear_jogador_button;
    private javax.swing.JButton elimina_aposta;
    private javax.swing.JButton eventos_desportivos_button;
    private javax.swing.JPanel eventos_desportivos_elements;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jogadores_bloq_button;
    private javax.swing.JPanel jogadores_bloqueados_elements;
    private javax.swing.JTable jogadores_list;
    private javax.swing.JTable lista_apostas;
    private javax.swing.ButtonGroup opcoes_aposta;
    private javax.swing.JPanel options_panel;
    private javax.swing.JButton remover_jogador_button;
    private javax.swing.JButton ver_jogadores_button;
    private javax.swing.JPanel ver_jogadores_elements;
    // End of variables declaration//GEN-END:variables
}
