/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package betess;

import java.text.DecimalFormat;
import java.util.*;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.table.DefaultTableModel;


public class AreaAdministrador extends javax.swing.JFrame {
    
    private BetESS betess;

    public void setBetess(BetESS betess) {
        this.betess = betess;
        this.setTitle("Área de administração");
    }

    /**
     * Creates new form AreaCliente
     */
    public AreaAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcoes_aposta = new javax.swing.ButtonGroup();
        Welcome_label = new javax.swing.JLabel();
        buttons_panel = new javax.swing.JPanel();
        ver_jogadores_button = new javax.swing.JButton();
        eventos_desportivos_button = new javax.swing.JButton();
        jogadores_bloq_button = new javax.swing.JButton();
        apostas_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nova_equipa_button = new javax.swing.JButton();
        nova_liga_button = new javax.swing.JButton();
        terminar_sessao_button = new javax.swing.JButton();
        options_panel = new javax.swing.JPanel();
        ver_jogadores_elements = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jogadores_list = new javax.swing.JTable();
        remover_jogador_button = new javax.swing.JButton();
        bloquear_jogador_button = new javax.swing.JButton();
        eventos_desportivos_elements = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        eventos_lista = new javax.swing.JTable();
        fechar_evento_button = new javax.swing.JButton();
        registar_evento_button = new javax.swing.JButton();
        jogadores_bloqueados_elements = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        desbloquear_jogador_button = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jogadores_bloqueados_list = new javax.swing.JTable();
        apostas_elements = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lista_apostas = new javax.swing.JTable();
        elimina_aposta = new javax.swing.JButton();
        novo_evento_elements = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        combo_casa = new javax.swing.JComboBox<>();
        combo_fora = new javax.swing.JComboBox<>();
        regista_evento_button = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        odd_casa_field = new javax.swing.JTextField();
        odd_fora_field = new javax.swing.JTextField();
        odd_empate_field = new javax.swing.JTextField();
        nova_equipa_elements = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nome_equipa_field = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ligas_combo = new javax.swing.JComboBox<>();
        regista_equipa_button = new javax.swing.JButton();
        nova_liga_elements = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        nome_liga_field = new javax.swing.JTextField();
        regista_liga_button = new javax.swing.JButton();
        fechar_evento_elements = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        evento_ganha_casa = new javax.swing.JRadioButton();
        evento_ganha_fora = new javax.swing.JRadioButton();
        evento_empate = new javax.swing.JRadioButton();
        fecha_evento_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Welcome_label.setText("Administração do Sistema");

        ver_jogadores_button.setText("Ver Jogadores");
        ver_jogadores_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_jogadores_buttonActionPerformed(evt);
            }
        });

        eventos_desportivos_button.setText("Eventos Desportivos");
        eventos_desportivos_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventos_desportivos_buttonActionPerformed(evt);
            }
        });

        jogadores_bloq_button.setText("Jogadores Bloqueados");
        jogadores_bloq_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogadores_bloq_buttonActionPerformed(evt);
            }
        });

        apostas_button.setText("Apostas");
        apostas_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apostas_buttonActionPerformed(evt);
            }
        });

        jLabel1.setText("Menu:");

        nova_equipa_button.setText("Nova Equipa");
        nova_equipa_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nova_equipa_buttonActionPerformed(evt);
            }
        });

        nova_liga_button.setText("Nova Liga");
        nova_liga_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nova_liga_buttonActionPerformed(evt);
            }
        });

        terminar_sessao_button.setText("Terminar Sessão");
        terminar_sessao_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminar_sessao_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttons_panelLayout = new javax.swing.GroupLayout(buttons_panel);
        buttons_panel.setLayout(buttons_panelLayout);
        buttons_panelLayout.setHorizontalGroup(
            buttons_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttons_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(69, 69, 69))
            .addGroup(buttons_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttons_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ver_jogadores_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jogadores_bloq_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(apostas_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eventos_desportivos_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nova_equipa_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nova_liga_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(terminar_sessao_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        buttons_panelLayout.setVerticalGroup(
            buttons_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttons_panelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(ver_jogadores_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eventos_desportivos_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jogadores_bloq_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(apostas_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nova_equipa_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nova_liga_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(terminar_sessao_button)
                .addContainerGap())
        );

        options_panel.setLayout(new java.awt.CardLayout());

        jLabel2.setText("Lista de Jogadores registados no sistema");

        jogadores_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Email", "Nome", "Contacto", "Saldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jogadores_list);
        if (jogadores_list.getColumnModel().getColumnCount() > 0) {
            jogadores_list.getColumnModel().getColumn(0).setResizable(false);
            jogadores_list.getColumnModel().getColumn(1).setResizable(false);
            jogadores_list.getColumnModel().getColumn(2).setResizable(false);
            jogadores_list.getColumnModel().getColumn(3).setResizable(false);
        }

        remover_jogador_button.setText("Remover");
        remover_jogador_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remover_jogador_buttonActionPerformed(evt);
            }
        });

        bloquear_jogador_button.setText("Bloquear");
        bloquear_jogador_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloquear_jogador_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ver_jogadores_elementsLayout = new javax.swing.GroupLayout(ver_jogadores_elements);
        ver_jogadores_elements.setLayout(ver_jogadores_elementsLayout);
        ver_jogadores_elementsLayout.setHorizontalGroup(
            ver_jogadores_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ver_jogadores_elementsLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(ver_jogadores_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(ver_jogadores_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(ver_jogadores_elementsLayout.createSequentialGroup()
                            .addComponent(bloquear_jogador_button)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(remover_jogador_button))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        ver_jogadores_elementsLayout.setVerticalGroup(
            ver_jogadores_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ver_jogadores_elementsLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ver_jogadores_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(remover_jogador_button)
                    .addComponent(bloquear_jogador_button))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        options_panel.add(ver_jogadores_elements, "card2");

        jLabel5.setText("Eventos Desportivos");

        eventos_lista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificador", "Equipa Casa", "Equipa Fora", "Ganha Casa", "Ganha Fora", "Empate", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(eventos_lista);
        if (eventos_lista.getColumnModel().getColumnCount() > 0) {
            eventos_lista.getColumnModel().getColumn(0).setResizable(false);
            eventos_lista.getColumnModel().getColumn(1).setResizable(false);
            eventos_lista.getColumnModel().getColumn(2).setResizable(false);
            eventos_lista.getColumnModel().getColumn(3).setResizable(false);
            eventos_lista.getColumnModel().getColumn(4).setResizable(false);
            eventos_lista.getColumnModel().getColumn(5).setResizable(false);
            eventos_lista.getColumnModel().getColumn(6).setResizable(false);
        }

        fechar_evento_button.setText("Fechar Evento");
        fechar_evento_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechar_evento_buttonActionPerformed(evt);
            }
        });

        registar_evento_button.setText("Registar Evento Desportivo");
        registar_evento_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registar_evento_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout eventos_desportivos_elementsLayout = new javax.swing.GroupLayout(eventos_desportivos_elements);
        eventos_desportivos_elements.setLayout(eventos_desportivos_elementsLayout);
        eventos_desportivos_elementsLayout.setHorizontalGroup(
            eventos_desportivos_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eventos_desportivos_elementsLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(eventos_desportivos_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(eventos_desportivos_elementsLayout.createSequentialGroup()
                        .addComponent(registar_evento_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fechar_evento_button))
                    .addGroup(eventos_desportivos_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        eventos_desportivos_elementsLayout.setVerticalGroup(
            eventos_desportivos_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eventos_desportivos_elementsLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(eventos_desportivos_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechar_evento_button)
                    .addComponent(registar_evento_button))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        options_panel.add(eventos_desportivos_elements, "card2");

        jLabel3.setText("Jogadores Bloqueados na Plataforma");

        desbloquear_jogador_button.setText("Desbloquear Jogador");
        desbloquear_jogador_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desbloquear_jogador_buttonActionPerformed(evt);
            }
        });

        jogadores_bloqueados_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Email", "Nome", "Contacto", "Saldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jogadores_bloqueados_list);
        if (jogadores_bloqueados_list.getColumnModel().getColumnCount() > 0) {
            jogadores_bloqueados_list.getColumnModel().getColumn(0).setResizable(false);
            jogadores_bloqueados_list.getColumnModel().getColumn(1).setResizable(false);
            jogadores_bloqueados_list.getColumnModel().getColumn(2).setResizable(false);
            jogadores_bloqueados_list.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jogadores_bloqueados_elementsLayout = new javax.swing.GroupLayout(jogadores_bloqueados_elements);
        jogadores_bloqueados_elements.setLayout(jogadores_bloqueados_elementsLayout);
        jogadores_bloqueados_elementsLayout.setHorizontalGroup(
            jogadores_bloqueados_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jogadores_bloqueados_elementsLayout.createSequentialGroup()
                .addGroup(jogadores_bloqueados_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jogadores_bloqueados_elementsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jogadores_bloqueados_elementsLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jogadores_bloqueados_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(desbloquear_jogador_button)
                            .addGroup(jogadores_bloqueados_elementsLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(410, 410, 410)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jogadores_bloqueados_elementsLayout.setVerticalGroup(
            jogadores_bloqueados_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jogadores_bloqueados_elementsLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desbloquear_jogador_button)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        options_panel.add(jogadores_bloqueados_elements, "card2");

        jLabel4.setText("Apostas");

        lista_apostas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificador", "Identificador Evento", "Identificador Jogador", "Ganha Casa", "Ganha Fora", "Empate", "Quantia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(lista_apostas);

        elimina_aposta.setText("Eliminar");
        elimina_aposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elimina_apostaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout apostas_elementsLayout = new javax.swing.GroupLayout(apostas_elements);
        apostas_elements.setLayout(apostas_elementsLayout);
        apostas_elementsLayout.setHorizontalGroup(
            apostas_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(apostas_elementsLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(apostas_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(elimina_aposta)
                    .addGroup(apostas_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        apostas_elementsLayout.setVerticalGroup(
            apostas_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(apostas_elementsLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(elimina_aposta)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        options_panel.add(apostas_elements, "card2");

        jLabel6.setText("Novo Evento Desportivo");

        jLabel7.setText("Equipa Casa:");

        jLabel8.setText("Equipa Fora:");

        regista_evento_button.setText("Registar Evento");
        regista_evento_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regista_evento_buttonActionPerformed(evt);
            }
        });

        jLabel14.setText("Odd Casa:");

        jLabel15.setText("Odd Fora:");

        jLabel16.setText("Odd Empate:");

        javax.swing.GroupLayout novo_evento_elementsLayout = new javax.swing.GroupLayout(novo_evento_elements);
        novo_evento_elements.setLayout(novo_evento_elementsLayout);
        novo_evento_elementsLayout.setHorizontalGroup(
            novo_evento_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, novo_evento_elementsLayout.createSequentialGroup()
                .addContainerGap(446, Short.MAX_VALUE)
                .addComponent(regista_evento_button)
                .addGap(124, 124, 124))
            .addGroup(novo_evento_elementsLayout.createSequentialGroup()
                .addGroup(novo_evento_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(novo_evento_elementsLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel6))
                    .addGroup(novo_evento_elementsLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(novo_evento_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(novo_evento_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8))
                            .addGroup(novo_evento_elementsLayout.createSequentialGroup()
                                .addGroup(novo_evento_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(3, 3, 3)))
                        .addGroup(novo_evento_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(combo_casa, 0, 222, Short.MAX_VALUE)
                            .addComponent(combo_fora, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(odd_empate_field, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(odd_casa_field)
                            .addComponent(odd_fora_field))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        novo_evento_elementsLayout.setVerticalGroup(
            novo_evento_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(novo_evento_elementsLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel6)
                .addGap(41, 41, 41)
                .addGroup(novo_evento_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(combo_casa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(novo_evento_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_fora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(novo_evento_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(odd_casa_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(novo_evento_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(odd_fora_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(novo_evento_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(odd_empate_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(regista_evento_button)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        options_panel.add(novo_evento_elements, "card2");

        jLabel9.setText("Nova Equipa");

        jLabel10.setText("Nome da equipa:");

        jLabel11.setText("Liga:");

        ligas_combo.setToolTipText("");

        regista_equipa_button.setText("Registar Equipa");
        regista_equipa_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regista_equipa_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nova_equipa_elementsLayout = new javax.swing.GroupLayout(nova_equipa_elements);
        nova_equipa_elements.setLayout(nova_equipa_elementsLayout);
        nova_equipa_elementsLayout.setHorizontalGroup(
            nova_equipa_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nova_equipa_elementsLayout.createSequentialGroup()
                .addGroup(nova_equipa_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nova_equipa_elementsLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel9))
                    .addGroup(nova_equipa_elementsLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(nova_equipa_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(regista_equipa_button)
                            .addGroup(nova_equipa_elementsLayout.createSequentialGroup()
                                .addGroup(nova_equipa_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(nova_equipa_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nome_equipa_field, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ligas_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        nova_equipa_elementsLayout.setVerticalGroup(
            nova_equipa_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nova_equipa_elementsLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel9)
                .addGap(30, 30, 30)
                .addGroup(nova_equipa_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(nome_equipa_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(nova_equipa_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(ligas_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(regista_equipa_button)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        options_panel.add(nova_equipa_elements, "card2");

        jLabel12.setText("Nova Liga");

        jLabel13.setText("Nome da Liga:");

        regista_liga_button.setText("Registar Liga");
        regista_liga_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regista_liga_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nova_liga_elementsLayout = new javax.swing.GroupLayout(nova_liga_elements);
        nova_liga_elements.setLayout(nova_liga_elementsLayout);
        nova_liga_elementsLayout.setHorizontalGroup(
            nova_liga_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nova_liga_elementsLayout.createSequentialGroup()
                .addGroup(nova_liga_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(regista_liga_button)
                    .addGroup(nova_liga_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(nova_liga_elementsLayout.createSequentialGroup()
                            .addGap(61, 61, 61)
                            .addComponent(jLabel12))
                        .addGroup(nova_liga_elementsLayout.createSequentialGroup()
                            .addGap(83, 83, 83)
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(nome_liga_field, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        nova_liga_elementsLayout.setVerticalGroup(
            nova_liga_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nova_liga_elementsLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel12)
                .addGap(30, 30, 30)
                .addGroup(nova_liga_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(nome_liga_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(regista_liga_button)
                .addContainerGap(248, Short.MAX_VALUE))
        );

        options_panel.add(nova_liga_elements, "card2");

        jLabel18.setText("Resultado do Evento:");

        opcoes_aposta.add(evento_ganha_casa);
        evento_ganha_casa.setText("Ganha Casa");

        opcoes_aposta.add(evento_ganha_fora);
        evento_ganha_fora.setText("Ganha Fora");

        opcoes_aposta.add(evento_empate);
        evento_empate.setText("Empate");

        fecha_evento_button.setText("Fechar");
        fecha_evento_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecha_evento_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fechar_evento_elementsLayout = new javax.swing.GroupLayout(fechar_evento_elements);
        fechar_evento_elements.setLayout(fechar_evento_elementsLayout);
        fechar_evento_elementsLayout.setHorizontalGroup(
            fechar_evento_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fechar_evento_elementsLayout.createSequentialGroup()
                .addGroup(fechar_evento_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fechar_evento_elementsLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel18))
                    .addGroup(fechar_evento_elementsLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(evento_ganha_casa)
                        .addGap(18, 18, 18)
                        .addComponent(evento_ganha_fora)
                        .addGap(18, 18, 18)
                        .addGroup(fechar_evento_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fecha_evento_button)
                            .addComponent(evento_empate))))
                .addContainerGap(253, Short.MAX_VALUE))
        );
        fechar_evento_elementsLayout.setVerticalGroup(
            fechar_evento_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fechar_evento_elementsLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addGroup(fechar_evento_elementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(evento_ganha_casa)
                    .addComponent(evento_ganha_fora)
                    .addComponent(evento_empate))
                .addGap(44, 44, 44)
                .addComponent(fecha_evento_button)
                .addContainerGap(227, Short.MAX_VALUE))
        );

        options_panel.add(fechar_evento_elements, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttons_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(Welcome_label)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(options_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Welcome_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(options_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttons_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eventos_desportivos_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventos_desportivos_buttonActionPerformed
        /* remoção de paineis anteriores */
        options_panel.removeAll();
        options_panel.repaint();
        options_panel.revalidate();
        
        /* alocação do respetivo painel de opções */
        options_panel.add(eventos_desportivos_elements);
        options_panel.repaint();
        options_panel.revalidate();
        
        DefaultTableModel model = (DefaultTableModel) eventos_lista.getModel();
        
        model.setRowCount(0);
        
        for (EventoDesportivo e : this.betess.getEventosDesportivos().values()){
            String equipa_casa = this.betess.getEquipa(e.getequipa_casa()).getDesignacao();
            String equipa_fora = this.betess.getEquipa(e.getequipa_fora()).getDesignacao();
            model.addRow(new Object[]{e.getId_evento(), equipa_casa, equipa_fora, e.getGanha_casa(), e.getGanha_fora(), e.getEmpate(), e.getEstado()});
        }
        
        
    }//GEN-LAST:event_eventos_desportivos_buttonActionPerformed

    private void ver_jogadores_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_jogadores_buttonActionPerformed
        /* remoção de paineis anteriores */
        options_panel.removeAll();
        options_panel.repaint();
        options_panel.revalidate();
        
        /* alocação do respetivo painel de opções */
        options_panel.add(ver_jogadores_elements);
        options_panel.repaint();
        options_panel.revalidate();
        
        HashMap<String, Jogador> jogadores = this.betess.getJogadores();
        
        DefaultTableModel model = (DefaultTableModel) jogadores_list.getModel();
        
        model.setRowCount(0);
        
        DecimalFormat dc = new DecimalFormat("0.00");
        
        for (Jogador j : jogadores.values()){
            model.addRow(new Object[]{j.getEmail(), j.getNome(), j.getContacto(), Double.parseDouble(dc.format(j.getSaldo()))});
        }
        
    }//GEN-LAST:event_ver_jogadores_buttonActionPerformed

    private void apostas_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apostas_buttonActionPerformed
        /* remoção de paineis anteriores */
        options_panel.removeAll();
        options_panel.repaint();
        options_panel.revalidate();
        
        /* alocação do respetivo painel de opções */
        options_panel.add(apostas_elements);
        options_panel.repaint();
        options_panel.revalidate();
        
        HashMap<Integer, Aposta> apostas = this.betess.getApostas();
        
        DefaultTableModel model = (DefaultTableModel) lista_apostas.getModel();
        
        model.setRowCount(0);
        
        DecimalFormat dc = new DecimalFormat("0.00");
        
        for (Aposta a : apostas.values()){
            EventoDesportivo e = this.betess.getEventoDesportivo(a.getId_evento());
            /*String equipa_casa = this.betess.getEquipa(e.getId_equipa_casa()).getDesignacao();
            String equipa_fora = this.betess.getEquipa(e.getId_equipa_fora()).getDesignacao();*/
            model.addRow(new Object[]{a.getId_aposta(), a.getId_evento(), a.getId_jogador(), a.getGanha_casa(), a.getGanha_fora(), a.getEmpate(), Double.parseDouble(dc.format(a.getQuantia()))});
        }
        
    }//GEN-LAST:event_apostas_buttonActionPerformed

    private void remover_jogador_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remover_jogador_buttonActionPerformed
        
        if (jogadores_bloqueados_list.getSelectedRow() != -1){

            int row = jogadores_list.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) jogadores_list.getModel();

            this.betess.eliminaJogador((String) jogadores_list.getValueAt(row, 0));
            model.removeRow(row);
        }
        else {
            JOptionPane.showMessageDialog(null, "Selecione um dos jogadores.", "Erro!", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_remover_jogador_buttonActionPerformed

    private void bloquear_jogador_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloquear_jogador_buttonActionPerformed
        
        if (jogadores_list.getSelectedRow() != -1){

            int row = jogadores_list.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) jogadores_list.getModel();

            this.betess.bloqueiaJogador((String) jogadores_list.getValueAt(row, 0));
            model.removeRow(row);
        }
        else {
            JOptionPane.showMessageDialog(null, "Selecione um dos jogadores.", "Erro!", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bloquear_jogador_buttonActionPerformed

    private void desbloquear_jogador_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desbloquear_jogador_buttonActionPerformed
        
        if (jogadores_bloqueados_list.getSelectedRow() != -1){

            int row = jogadores_bloqueados_list.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) jogadores_bloqueados_list.getModel();

            this.betess.desbloqueiaJogador((String) jogadores_bloqueados_list.getValueAt(row, 0));
            model.removeRow(row);
        }
        else {
            JOptionPane.showMessageDialog(null, "Selecione um dos jogadores.", "Erro!", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_desbloquear_jogador_buttonActionPerformed

    private void elimina_apostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elimina_apostaActionPerformed
        
        if ( lista_apostas.getSelectedRow() != -1){

            int row = lista_apostas.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) lista_apostas.getModel();

            this.betess.removeAposta((int)lista_apostas.getValueAt(row, 0));
            model.removeRow(row);
        }
        else {
            JOptionPane.showMessageDialog(null, "Selecione uma das apostas.", "Erro!", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_elimina_apostaActionPerformed

    private void fechar_evento_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechar_evento_buttonActionPerformed
        /* remoção de paineis anteriores */
        options_panel.removeAll();
        options_panel.repaint();
        options_panel.revalidate();
        
        /* alocação do respetivo painel de opções */
        options_panel.add(fechar_evento_elements);
        options_panel.repaint();
        options_panel.revalidate();
    }//GEN-LAST:event_fechar_evento_buttonActionPerformed

    private void registar_evento_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registar_evento_buttonActionPerformed
        /* remoção de paineis anteriores */
        options_panel.removeAll();
        options_panel.repaint();
        options_panel.revalidate();
        
        /* alocação do respetivo painel de opções */
        options_panel.add(novo_evento_elements);
        options_panel.repaint();
        options_panel.revalidate();
        
        List<Equipa> equipas = this.betess.getEquipas();
        
        combo_casa.removeAllItems();
        combo_fora.removeAllItems();
        
        for (Equipa e : equipas){
            combo_casa.addItem(e.getDesignacao());
            combo_fora.addItem(e.getDesignacao());
        }
    }//GEN-LAST:event_registar_evento_buttonActionPerformed

    private void regista_evento_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regista_evento_buttonActionPerformed
        
        if (!combo_casa.getSelectedItem().toString().isEmpty() &&
            !combo_fora.getSelectedItem().toString().isEmpty() &&
            !odd_casa_field.getText().isEmpty() &&
            !odd_fora_field.getText().isEmpty() &&
            !odd_empate_field.getText().isEmpty()){

            String c_casa = combo_casa.getSelectedItem().toString();                                                     
            String c_fora = combo_fora.getSelectedItem().toString();

            String odd_casa = odd_casa_field.getText();
            String odd_fora = odd_fora_field.getText();
            String odd_empate = odd_empate_field.getText();

            if (c_casa.equals(c_fora)){
                JOptionPane.showMessageDialog(null, "Não é possível definir um evento apenas com uma equipa.", "Falha no registo do evento desportivo", ERROR_MESSAGE);
            }
            else {
                this.betess.registaEventoDesportivo(c_casa, c_fora, Double.parseDouble(odd_casa), Double.parseDouble(odd_fora), Double.parseDouble(odd_empate));
                JOptionPane.showMessageDialog(null, "Evento registado com sucesso.", "BetESS", JOptionPane.PLAIN_MESSAGE);
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Existem campos do formulário não preenchidos.", "Erro!", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_regista_evento_buttonActionPerformed

    private void nova_equipa_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nova_equipa_buttonActionPerformed
        /* remoção de paineis anteriores */
        options_panel.removeAll();
        options_panel.repaint();
        options_panel.revalidate();
        
        /* alocação do respetivo painel de opções */
        options_panel.add(nova_equipa_elements);
        options_panel.repaint();
        options_panel.revalidate();
        
        List<Liga> ligas = this.betess.getLigas();
        
        ligas_combo.removeAllItems();
        
        for (Liga l : ligas){
            ligas_combo.addItem(l.getNome());
        }
    }//GEN-LAST:event_nova_equipa_buttonActionPerformed

    private void nova_liga_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nova_liga_buttonActionPerformed
        /* remoção de paineis anteriores */
        options_panel.removeAll();
        options_panel.repaint();
        options_panel.revalidate();
        
        /* alocação do respetivo painel de opções */
        options_panel.add(nova_liga_elements);
        options_panel.repaint();
        options_panel.revalidate();
    }//GEN-LAST:event_nova_liga_buttonActionPerformed

    private void regista_liga_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regista_liga_buttonActionPerformed
        
        if (!nome_liga_field.getText().isEmpty()){

            List<Liga> ligas = this.betess.getLigas();

            String nome_liga = nome_liga_field.getText();

            boolean permite_liga = true;
            for (Liga l: ligas){
                if (l.getNome().equals(nome_liga)){
                    permite_liga = false;
                    break;
                }
            }
            if (permite_liga){
                Liga l = new Liga(nome_liga);
                this.betess.registaLiga(l);
            }
            else {
                JOptionPane.showMessageDialog(null, "Já existe uma Liga registada no sistema com o nome indicado.", "Falha no registo da liga", JOptionPane.ERROR_MESSAGE);
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Existem campos do formulário não preenchidos.", "Erro!", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_regista_liga_buttonActionPerformed

    private void terminar_sessao_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminar_sessao_buttonActionPerformed
        this.betess.setId_utilizador_aut("None");
        this.setVisible(false);
        
        /* local onde o estado da aplicação é guardado */
        this.betess.save();
    }//GEN-LAST:event_terminar_sessao_buttonActionPerformed

    private void regista_equipa_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regista_equipa_buttonActionPerformed

        if (!nome_equipa_field.getText().isEmpty() &&
            ligas_combo.getSelectedItem() != null){

            String nome_equipa = nome_equipa_field.getText();
            String liga = (String) ligas_combo.getSelectedItem();

            this.betess.registaEquipa(new Equipa(liga, nome_equipa));
        }
        else {
            JOptionPane.showMessageDialog(null, "Existem campos do formulário não preenchidos.", "Erro!", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_regista_equipa_buttonActionPerformed

    private void jogadores_bloq_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jogadores_bloq_buttonActionPerformed
        /* remoção de paineis anteriores */
        options_panel.removeAll();
        options_panel.repaint();
        options_panel.revalidate();
        
        /* alocação do respetivo painel de opções */
        options_panel.add(jogadores_bloqueados_elements);
        options_panel.repaint();
        options_panel.revalidate();
        
        DefaultTableModel model = (DefaultTableModel) jogadores_bloqueados_list.getModel();
        
        List<Jogador> jogadores = this.betess.getJogadoresBloqueados();
        
        model.setRowCount(0);
        
        DecimalFormat dc = new DecimalFormat("0.00");
        
        for (Jogador j : jogadores){
            model.addRow(new Object[]{j.getEmail(), j.getNome(), j.getContacto(), Double.parseDouble(dc.format(j.getSaldo()))});
        }
    }//GEN-LAST:event_jogadores_bloq_buttonActionPerformed

    private void fecha_evento_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecha_evento_buttonActionPerformed
        
        if (opcoes_aposta.getSelection() != null){

            boolean ganha_casa = evento_ganha_casa.isSelected();
            boolean ganha_fora = evento_ganha_fora.isSelected();
            boolean empate = evento_empate.isSelected();

            int row = eventos_lista.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) eventos_lista.getModel();

            int id_evento = (int) model.getValueAt(row, 0);
            this.betess.fechaEvento(id_evento, ganha_casa, ganha_fora, empate);

            /* remoção de paineis anteriores */
            options_panel.removeAll();
            options_panel.repaint();
            options_panel.revalidate();

            /* alocação do respetivo painel de opções */
            options_panel.add(eventos_desportivos_elements);
            options_panel.repaint();
            options_panel.revalidate();
        }
        else {
            JOptionPane.showMessageDialog(null, "Existem campos do formulário não preenchidos.", "Erro!", ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_fecha_evento_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AreaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AreaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AreaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AreaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AreaAdministrador main = new AreaAdministrador();
                main.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Welcome_label;
    private javax.swing.JButton apostas_button;
    private javax.swing.JPanel apostas_elements;
    private javax.swing.JButton bloquear_jogador_button;
    private javax.swing.JPanel buttons_panel;
    private javax.swing.JComboBox<String> combo_casa;
    private javax.swing.JComboBox<String> combo_fora;
    private javax.swing.JButton desbloquear_jogador_button;
    private javax.swing.JButton elimina_aposta;
    private javax.swing.JRadioButton evento_empate;
    private javax.swing.JRadioButton evento_ganha_casa;
    private javax.swing.JRadioButton evento_ganha_fora;
    private javax.swing.JButton eventos_desportivos_button;
    private javax.swing.JPanel eventos_desportivos_elements;
    private javax.swing.JTable eventos_lista;
    private javax.swing.JButton fecha_evento_button;
    private javax.swing.JButton fechar_evento_button;
    private javax.swing.JPanel fechar_evento_elements;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton jogadores_bloq_button;
    private javax.swing.JPanel jogadores_bloqueados_elements;
    private javax.swing.JTable jogadores_bloqueados_list;
    private javax.swing.JTable jogadores_list;
    private javax.swing.JComboBox<String> ligas_combo;
    private javax.swing.JTable lista_apostas;
    private javax.swing.JTextField nome_equipa_field;
    private javax.swing.JTextField nome_liga_field;
    private javax.swing.JButton nova_equipa_button;
    private javax.swing.JPanel nova_equipa_elements;
    private javax.swing.JButton nova_liga_button;
    private javax.swing.JPanel nova_liga_elements;
    private javax.swing.JPanel novo_evento_elements;
    private javax.swing.JTextField odd_casa_field;
    private javax.swing.JTextField odd_empate_field;
    private javax.swing.JTextField odd_fora_field;
    private javax.swing.ButtonGroup opcoes_aposta;
    private javax.swing.JPanel options_panel;
    private javax.swing.JButton regista_equipa_button;
    private javax.swing.JButton regista_evento_button;
    private javax.swing.JButton regista_liga_button;
    private javax.swing.JButton registar_evento_button;
    private javax.swing.JButton remover_jogador_button;
    private javax.swing.JButton terminar_sessao_button;
    private javax.swing.JButton ver_jogadores_button;
    private javax.swing.JPanel ver_jogadores_elements;
    // End of variables declaration//GEN-END:variables
}
